# Generated by Django 6.0.2 on 2026-02-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='caption',
            new_name='description',
        ),
    ]
